name: Tag and Release

on:
  push:
    branches: main

jobs:
  tag-release:
    name: Tag and Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version
        id: version
        run: echo ::set-output name=tag::$(git tag -l | sort -V -r | head -n 1)
      - name: Bump version
        id: bump-version
        uses: ./.github/actions/bump-version
        with:
          tag: ${{ steps.version.outputs.tag }}
      - name: Tag
        run: |
          git tag -f v1
          git push -f --tags
      - name: Release
        run: gh release create ${{ steps.bump-version.outputs.tag }}